export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SEARCH_AUTHOR = 'SEARCH_AUTHOR';
export const SEARCH_ASYNC_AUTHOR = 'SEARCH_ASYNC_AUTHOR';
export const IS_LOADING = 'IS_LOADING';

